# Generated by Django 5.0.6 on 2024-06-29 04:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0011_alter_donation_amount'),
    ]

    operations = [
        migrations.AddField(
            model_name='volunteeringevent',
            name='donation_goal',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='donation',
            name='amount',
            field=models.PositiveIntegerField(choices=[(0, '$0'), (20, '$20'), (50, '$50'), (100, '$100'), (200, '$200')], default=0),
        ),
    ]
